<div class="socnet facepile">
<?php if($this->getMode() == Phi_Socnet_Helper_Data::FACEBOOK_HTML5_MODE):?>
<?php Mage::log("Html5 mode not yet implemented");?>
<?php elseif ($this->getMode() == Phi_Socnet_Helper_Data::FACEBOOK_XFBML_MODE): ?>
<fb:like send="<?php echo $this->getSendData()?>"
	layout="<?php echo $this->getFbLayout()?>"
	width="<?php echo $this->getWidth()?>"
	show-faces="<?php echo $this->getShowFaces()?>"
	<?php if($this->getShowRef()):?>
		ref="<?php echo $this->getRef()?>"
	<?php endif;?>
	font="<?php echo $this->getFont()?>">
</fb:like>
<?php else: ?>
<?php Mage::log("Iframe mode not yet implemented");?>
<?php endif;?>
</div>