<div class="socnet login-button">
    <?php if($this->getMode() == Phi_Socnet_Helper_Data::FACEBOOK_HTML5_MODE):?>
    <?php Mage::log("Html5 mode not yet implemented");?>
    <div
    	class="fb-login-button"
    	data-show-faces="<?php echo $this->getShowfaces() ?>"
    	data-width="<?php echo $this->getWidth() ?>"
    	data-max-rows="<?php echo $this->getDataMaxRows() ?>"></div>
    <?php elseif ($this->getMode() == Phi_Socnet_Helper_Data::FACEBOOK_XFBML_MODE): ?>
    <fb:login-button
        <?php if($this->showRegistration()): ?>
            registration-url="<?php echo $this->getRegisterUrl()?>"
        <?php endif;?>
        show-faces="<?php echo $this->getShowfaces() ?>"
    	width="<?php echo $this->getWidth() ?>"
    	max-rows="<?php echo $this->getDataMaxRows() ?>">
    </fb:login-button>
    <?php else: ?>
    <?php Mage::log("Iframe mode not yet implemented");?>
    <?php endif;?>
</div>